# Generated by Django 4.1 on 2022-09-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palantiriAPI', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='circle_posts', to='palantiriAPI.circle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circler_circle', to='palantiriAPI.circler'),
        ),
        migrations.AlterField(
            model_name='circlemember',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_members', to='palantiriAPI.circle'),
        ),
        migrations.AlterField(
            model_name='circlemember',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circler_membership', to='palantiriAPI.circler'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circler_comments', to='palantiriAPI.circler'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_invitees', to='palantiriAPI.circle'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_invites', to='palantiriAPI.circler'),
        ),
        migrations.AlterField(
            model_name='message',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_messages', to='palantiriAPI.circle'),
        ),
        migrations.AlterField(
            model_name='message',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circler_messages', to='palantiriAPI.circler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='circler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circler_posts', to='palantiriAPI.circler'),
        ),
    ]
